// Code generated by MockGen. DO NOT EDIT.
// Source: watch.go
//
// Generated by this command:
//
//	mockgen -source=watch.go -destination=mock/mock_watch.go -package=mock_ranking
//

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	context "context"
	reflect "reflect"

	ranking "github.com/uchidas-rogue/game-api-sample/internal/usecase/ranking"
	gomock "go.uber.org/mock/gomock"
)

// MockRankingUpdateNotifier is a mock of RankingUpdateNotifier interface.
type MockRankingUpdateNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRankingUpdateNotifierMockRecorder
	isgomock struct{}
}

// MockRankingUpdateNotifierMockRecorder is the mock recorder for MockRankingUpdateNotifier.
type MockRankingUpdateNotifierMockRecorder struct {
	mock *MockRankingUpdateNotifier
}

// NewMockRankingUpdateNotifier creates a new mock instance.
func NewMockRankingUpdateNotifier(ctrl *gomock.Controller) *MockRankingUpdateNotifier {
	mock := &MockRankingUpdateNotifier{ctrl: ctrl}
	mock.recorder = &MockRankingUpdateNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingUpdateNotifier) EXPECT() *MockRankingUpdateNotifierMockRecorder {
	return m.recorder
}

// NotifyUpdated mocks base method.
func (m *MockRankingUpdateNotifier) NotifyUpdated(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUpdated", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyUpdated indicates an expected call of NotifyUpdated.
func (mr *MockRankingUpdateNotifierMockRecorder) NotifyUpdated(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUpdated", reflect.TypeOf((*MockRankingUpdateNotifier)(nil).NotifyUpdated), ctx)
}

// MockRankingUpdateSubscriber is a mock of RankingUpdateSubscriber interface.
type MockRankingUpdateSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockRankingUpdateSubscriberMockRecorder
	isgomock struct{}
}

// MockRankingUpdateSubscriberMockRecorder is the mock recorder for MockRankingUpdateSubscriber.
type MockRankingUpdateSubscriberMockRecorder struct {
	mock *MockRankingUpdateSubscriber
}

// NewMockRankingUpdateSubscriber creates a new mock instance.
func NewMockRankingUpdateSubscriber(ctrl *gomock.Controller) *MockRankingUpdateSubscriber {
	mock := &MockRankingUpdateSubscriber{ctrl: ctrl}
	mock.recorder = &MockRankingUpdateSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingUpdateSubscriber) EXPECT() *MockRankingUpdateSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockRankingUpdateSubscriber) Subscribe(ctx context.Context) (<-chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockRankingUpdateSubscriberMockRecorder) Subscribe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockRankingUpdateSubscriber)(nil).Subscribe), ctx)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// WatchUserRankings mocks base method.
func (m *MockWatcher) WatchUserRankings(ctx context.Context, limit int) (<-chan ranking.RankingsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchUserRankings", ctx, limit)
	ret0, _ := ret[0].(<-chan ranking.RankingsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchUserRankings indicates an expected call of WatchUserRankings.
func (mr *MockWatcherMockRecorder) WatchUserRankings(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchUserRankings", reflect.TypeOf((*MockWatcher)(nil).WatchUserRankings), ctx, limit)
}
