// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock_ranking
//

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	context "context"
	reflect "reflect"

	ranking "github.com/uchidas-rogue/game-api-sample/internal/domain/ranking"
	shared "github.com/uchidas-rogue/game-api-sample/internal/usecase/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BulkIncrementGuildScores mocks base method.
func (m *MockRepository) BulkIncrementGuildScores(ctx context.Context, tx shared.Tx, deltas []ranking.GuildScoreDelta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkIncrementGuildScores", ctx, tx, deltas)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkIncrementGuildScores indicates an expected call of BulkIncrementGuildScores.
func (mr *MockRepositoryMockRecorder) BulkIncrementGuildScores(ctx, tx, deltas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkIncrementGuildScores", reflect.TypeOf((*MockRepository)(nil).BulkIncrementGuildScores), ctx, tx, deltas)
}

// BulkInsertGuildScoreHistories mocks base method.
func (m *MockRepository) BulkInsertGuildScoreHistories(ctx context.Context, tx shared.Tx, entries []ranking.GuildScoreHistoryEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertGuildScoreHistories", ctx, tx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertGuildScoreHistories indicates an expected call of BulkInsertGuildScoreHistories.
func (mr *MockRepositoryMockRecorder) BulkInsertGuildScoreHistories(ctx, tx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertGuildScoreHistories", reflect.TypeOf((*MockRepository)(nil).BulkInsertGuildScoreHistories), ctx, tx, entries)
}

// GetGuild mocks base method.
func (m *MockRepository) GetGuild(ctx context.Context, tx shared.Tx, guildID int64) (ranking.Guild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuild", ctx, tx, guildID)
	ret0, _ := ret[0].(ranking.Guild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuild indicates an expected call of GetGuild.
func (mr *MockRepositoryMockRecorder) GetGuild(ctx, tx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuild", reflect.TypeOf((*MockRepository)(nil).GetGuild), ctx, tx, guildID)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, tx shared.Tx, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, tx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, tx, userID)
}

// GetUserGuildID mocks base method.
func (m *MockRepository) GetUserGuildID(ctx context.Context, tx shared.Tx, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGuildID", ctx, tx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGuildID indicates an expected call of GetUserGuildID.
func (mr *MockRepositoryMockRecorder) GetUserGuildID(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGuildID", reflect.TypeOf((*MockRepository)(nil).GetUserGuildID), ctx, tx, userID)
}

// GetUserPoints mocks base method.
func (m *MockRepository) GetUserPoints(ctx context.Context, tx shared.Tx, userID int64) (ranking.UserPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPoints", ctx, tx, userID)
	ret0, _ := ret[0].(ranking.UserPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPoints indicates an expected call of GetUserPoints.
func (mr *MockRepositoryMockRecorder) GetUserPoints(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPoints", reflect.TypeOf((*MockRepository)(nil).GetUserPoints), ctx, tx, userID)
}

// IncrementGuildScore mocks base method.
func (m *MockRepository) IncrementGuildScore(ctx context.Context, tx shared.Tx, guildID, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGuildScore", ctx, tx, guildID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementGuildScore indicates an expected call of IncrementGuildScore.
func (mr *MockRepositoryMockRecorder) IncrementGuildScore(ctx, tx, guildID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGuildScore", reflect.TypeOf((*MockRepository)(nil).IncrementGuildScore), ctx, tx, guildID, score)
}

// IncrementUserPoints mocks base method.
func (m *MockRepository) IncrementUserPoints(ctx context.Context, tx shared.Tx, userID, points int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUserPoints", ctx, tx, userID, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUserPoints indicates an expected call of IncrementUserPoints.
func (mr *MockRepositoryMockRecorder) IncrementUserPoints(ctx, tx, userID, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUserPoints", reflect.TypeOf((*MockRepository)(nil).IncrementUserPoints), ctx, tx, userID, points)
}

// InsertGuildScoreHistory mocks base method.
func (m *MockRepository) InsertGuildScoreHistory(ctx context.Context, tx shared.Tx, guildID, userID, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGuildScoreHistory", ctx, tx, guildID, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGuildScoreHistory indicates an expected call of InsertGuildScoreHistory.
func (mr *MockRepositoryMockRecorder) InsertGuildScoreHistory(ctx, tx, guildID, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGuildScoreHistory", reflect.TypeOf((*MockRepository)(nil).InsertGuildScoreHistory), ctx, tx, guildID, userID, score)
}

// InsertUserPointHistory mocks base method.
func (m *MockRepository) InsertUserPointHistory(ctx context.Context, tx shared.Tx, userID, points int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserPointHistory", ctx, tx, userID, points, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserPointHistory indicates an expected call of InsertUserPointHistory.
func (mr *MockRepositoryMockRecorder) InsertUserPointHistory(ctx, tx, userID, points, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserPointHistory", reflect.TypeOf((*MockRepository)(nil).InsertUserPointHistory), ctx, tx, userID, points, reason)
}

// ListAllGuildScores mocks base method.
func (m *MockRepository) ListAllGuildScores(ctx context.Context, tx shared.Tx) ([]ranking.GuildScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllGuildScores", ctx, tx)
	ret0, _ := ret[0].([]ranking.GuildScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllGuildScores indicates an expected call of ListAllGuildScores.
func (mr *MockRepositoryMockRecorder) ListAllGuildScores(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllGuildScores", reflect.TypeOf((*MockRepository)(nil).ListAllGuildScores), ctx, tx)
}

// ListAllUserPoints mocks base method.
func (m *MockRepository) ListAllUserPoints(ctx context.Context, tx shared.Tx) ([]ranking.UserPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUserPoints", ctx, tx)
	ret0, _ := ret[0].([]ranking.UserPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUserPoints indicates an expected call of ListAllUserPoints.
func (mr *MockRepositoryMockRecorder) ListAllUserPoints(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUserPoints", reflect.TypeOf((*MockRepository)(nil).ListAllUserPoints), ctx, tx)
}

// ListGuildsByIDs mocks base method.
func (m *MockRepository) ListGuildsByIDs(ctx context.Context, tx shared.Tx, guildIDs []int64) (map[int64]ranking.Guild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGuildsByIDs", ctx, tx, guildIDs)
	ret0, _ := ret[0].(map[int64]ranking.Guild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGuildsByIDs indicates an expected call of ListGuildsByIDs.
func (mr *MockRepositoryMockRecorder) ListGuildsByIDs(ctx, tx, guildIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGuildsByIDs", reflect.TypeOf((*MockRepository)(nil).ListGuildsByIDs), ctx, tx, guildIDs)
}

// ListUsersByIDs mocks base method.
func (m *MockRepository) ListUsersByIDs(ctx context.Context, tx shared.Tx, userIDs []int64) (map[int64]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByIDs", ctx, tx, userIDs)
	ret0, _ := ret[0].(map[int64]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByIDs indicates an expected call of ListUsersByIDs.
func (mr *MockRepositoryMockRecorder) ListUsersByIDs(ctx, tx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByIDs", reflect.TypeOf((*MockRepository)(nil).ListUsersByIDs), ctx, tx, userIDs)
}

// MockRankingStore is a mock of RankingStore interface.
type MockRankingStore struct {
	ctrl     *gomock.Controller
	recorder *MockRankingStoreMockRecorder
	isgomock struct{}
}

// MockRankingStoreMockRecorder is the mock recorder for MockRankingStore.
type MockRankingStoreMockRecorder struct {
	mock *MockRankingStore
}

// NewMockRankingStore creates a new mock instance.
func NewMockRankingStore(ctrl *gomock.Controller) *MockRankingStore {
	mock := &MockRankingStore{ctrl: ctrl}
	mock.recorder = &MockRankingStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingStore) EXPECT() *MockRankingStoreMockRecorder {
	return m.recorder
}

// ApplyScoreDeltas mocks base method.
func (m *MockRankingStore) ApplyScoreDeltas(ctx context.Context, users []ranking.UserPointDelta, guilds []ranking.GuildScoreDelta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyScoreDeltas", ctx, users, guilds)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyScoreDeltas indicates an expected call of ApplyScoreDeltas.
func (mr *MockRankingStoreMockRecorder) ApplyScoreDeltas(ctx, users, guilds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyScoreDeltas", reflect.TypeOf((*MockRankingStore)(nil).ApplyScoreDeltas), ctx, users, guilds)
}

// GetGuildRank mocks base method.
func (m *MockRankingStore) GetGuildRank(ctx context.Context, guildID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildRank", ctx, guildID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildRank indicates an expected call of GetGuildRank.
func (mr *MockRankingStoreMockRecorder) GetGuildRank(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildRank", reflect.TypeOf((*MockRankingStore)(nil).GetGuildRank), ctx, guildID)
}

// GetGuildRankings mocks base method.
func (m *MockRankingStore) GetGuildRankings(ctx context.Context, offset, limit int) ([]ranking.RankEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildRankings", ctx, offset, limit)
	ret0, _ := ret[0].([]ranking.RankEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildRankings indicates an expected call of GetGuildRankings.
func (mr *MockRankingStoreMockRecorder) GetGuildRankings(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildRankings", reflect.TypeOf((*MockRankingStore)(nil).GetGuildRankings), ctx, offset, limit)
}

// GetGuildScore mocks base method.
func (m *MockRankingStore) GetGuildScore(ctx context.Context, guildID int64) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildScore", ctx, guildID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGuildScore indicates an expected call of GetGuildScore.
func (mr *MockRankingStoreMockRecorder) GetGuildScore(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildScore", reflect.TypeOf((*MockRankingStore)(nil).GetGuildScore), ctx, guildID)
}

// GetGuildTotalCount mocks base method.
func (m *MockRankingStore) GetGuildTotalCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildTotalCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildTotalCount indicates an expected call of GetGuildTotalCount.
func (mr *MockRankingStoreMockRecorder) GetGuildTotalCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildTotalCount", reflect.TypeOf((*MockRankingStore)(nil).GetGuildTotalCount), ctx)
}

// GetUserPoints mocks base method.
func (m *MockRankingStore) GetUserPoints(ctx context.Context, userID int64) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPoints", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserPoints indicates an expected call of GetUserPoints.
func (mr *MockRankingStoreMockRecorder) GetUserPoints(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPoints", reflect.TypeOf((*MockRankingStore)(nil).GetUserPoints), ctx, userID)
}

// GetUserRank mocks base method.
func (m *MockRankingStore) GetUserRank(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRank", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRank indicates an expected call of GetUserRank.
func (mr *MockRankingStoreMockRecorder) GetUserRank(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRank", reflect.TypeOf((*MockRankingStore)(nil).GetUserRank), ctx, userID)
}

// GetUserRankings mocks base method.
func (m *MockRankingStore) GetUserRankings(ctx context.Context, offset, limit int) ([]ranking.RankEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRankings", ctx, offset, limit)
	ret0, _ := ret[0].([]ranking.RankEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRankings indicates an expected call of GetUserRankings.
func (mr *MockRankingStoreMockRecorder) GetUserRankings(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRankings", reflect.TypeOf((*MockRankingStore)(nil).GetUserRankings), ctx, offset, limit)
}

// GetUserTotalCount mocks base method.
func (m *MockRankingStore) GetUserTotalCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTotalCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTotalCount indicates an expected call of GetUserTotalCount.
func (mr *MockRankingStoreMockRecorder) GetUserTotalCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTotalCount", reflect.TypeOf((*MockRankingStore)(nil).GetUserTotalCount), ctx)
}

// SetGuildScore mocks base method.
func (m *MockRankingStore) SetGuildScore(ctx context.Context, guildID, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGuildScore", ctx, guildID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGuildScore indicates an expected call of SetGuildScore.
func (mr *MockRankingStoreMockRecorder) SetGuildScore(ctx, guildID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGuildScore", reflect.TypeOf((*MockRankingStore)(nil).SetGuildScore), ctx, guildID, score)
}

// SetUserPoints mocks base method.
func (m *MockRankingStore) SetUserPoints(ctx context.Context, userID, points int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserPoints", ctx, userID, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserPoints indicates an expected call of SetUserPoints.
func (mr *MockRankingStoreMockRecorder) SetUserPoints(ctx, userID, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPoints", reflect.TypeOf((*MockRankingStore)(nil).SetUserPoints), ctx, userID, points)
}
