// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mock/mock_usecase.go -package=mock_ranking
//

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	context "context"
	reflect "reflect"

	ranking "github.com/uchidas-rogue/game-api-sample/internal/domain/ranking"
	ranking0 "github.com/uchidas-rogue/game-api-sample/internal/usecase/ranking"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AddUserPoints mocks base method.
func (m *MockUsecase) AddUserPoints(ctx context.Context, input ranking0.AddUserPointsInput) (ranking.UserPointAddResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserPoints", ctx, input)
	ret0, _ := ret[0].(ranking.UserPointAddResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserPoints indicates an expected call of AddUserPoints.
func (mr *MockUsecaseMockRecorder) AddUserPoints(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserPoints", reflect.TypeOf((*MockUsecase)(nil).AddUserPoints), ctx, input)
}

// GetGuildRank mocks base method.
func (m *MockUsecase) GetGuildRank(ctx context.Context, guildID int64) (ranking.GuildRankResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildRank", ctx, guildID)
	ret0, _ := ret[0].(ranking.GuildRankResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildRank indicates an expected call of GetGuildRank.
func (mr *MockUsecaseMockRecorder) GetGuildRank(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildRank", reflect.TypeOf((*MockUsecase)(nil).GetGuildRank), ctx, guildID)
}

// GetGuildRankings mocks base method.
func (m *MockUsecase) GetGuildRankings(ctx context.Context, input ranking0.GetRankingsInput) (ranking0.RankingsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildRankings", ctx, input)
	ret0, _ := ret[0].(ranking0.RankingsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildRankings indicates an expected call of GetGuildRankings.
func (mr *MockUsecaseMockRecorder) GetGuildRankings(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildRankings", reflect.TypeOf((*MockUsecase)(nil).GetGuildRankings), ctx, input)
}

// GetUserRank mocks base method.
func (m *MockUsecase) GetUserRank(ctx context.Context, userID int64) (ranking.UserRankResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRank", ctx, userID)
	ret0, _ := ret[0].(ranking.UserRankResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRank indicates an expected call of GetUserRank.
func (mr *MockUsecaseMockRecorder) GetUserRank(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRank", reflect.TypeOf((*MockUsecase)(nil).GetUserRank), ctx, userID)
}

// GetUserRankings mocks base method.
func (m *MockUsecase) GetUserRankings(ctx context.Context, input ranking0.GetRankingsInput) (ranking0.RankingsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRankings", ctx, input)
	ret0, _ := ret[0].(ranking0.RankingsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRankings indicates an expected call of GetUserRankings.
func (mr *MockUsecaseMockRecorder) GetUserRankings(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRankings", reflect.TypeOf((*MockUsecase)(nil).GetUserRankings), ctx, input)
}
