// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gacha.sql

package sqlc

import (
	"context"
)

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, name, gem_num, created_at, updated_at
FROM users
WHERE id = ?
FOR UPDATE
`

// ユーザー行を排他ロックで取得する。10連ガチャの整合性確保用。
// 必ずトランザクション内から呼び出すこと。デッドロック誘発検証のため意図的に FOR UPDATE。
func (q *Queries) GetUserForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GemNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, rarity, weight, created_at
FROM items
`

// アイテムマスタ全件を取得する（排出抽選用）。
func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rarity,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserGems = `-- name: UpdateUserGems :exec
UPDATE users
SET gem_num = ?
WHERE id = ?
`

type UpdateUserGemsParams struct {
	GemNum int32
	ID     int64
}

// 指定ユーザーの石残高を更新する。トランザクション内から呼び出す前提。
func (q *Queries) UpdateUserGems(ctx context.Context, arg UpdateUserGemsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGems, arg.GemNum, arg.ID)
	return err
}
