// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type GachaHistory struct {
	ID        int64
	UserID    int64
	ItemID    int64
	CreatedAt sql.NullTime
}

type Item struct {
	ID   int64
	Name string
	// レアリティ(1:N, 2:R, 3:SR, 4:SSR)
	Rarity int32
	// 排出確率計算用の重み
	Weight    int32
	CreatedAt sql.NullTime
}

type User struct {
	ID   int64
	Name string
	// ガチャ石の残高
	GemNum    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserItem struct {
	UserID int64
	ItemID int64
	// 所持数
	Num       int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
