// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deleteProcessedOutboxEventsBefore = `-- name: DeleteProcessedOutboxEventsBefore :exec
DELETE FROM outbox_events
WHERE processed_at IS NOT NULL
  AND processed_at < ?
`

func (q *Queries) DeleteProcessedOutboxEventsBefore(ctx context.Context, processedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteProcessedOutboxEventsBefore, processedAt)
	return err
}

const incrementOutboxEventRetry = `-- name: IncrementOutboxEventRetry :exec
UPDATE outbox_events
SET retry_count = retry_count + 1,
    last_error  = ?
WHERE id = ?
`

type IncrementOutboxEventRetryParams struct {
	LastError sql.NullString
	ID        uint64
}

func (q *Queries) IncrementOutboxEventRetry(ctx context.Context, arg IncrementOutboxEventRetryParams) error {
	_, err := q.db.ExecContext(ctx, incrementOutboxEventRetry, arg.LastError, arg.ID)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :execlastid
INSERT INTO outbox_events (event_type, payload)
VALUES (?, ?)
`

type InsertOutboxEventParams struct {
	EventType string
	Payload   json.RawMessage
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOutboxEvent, arg.EventType, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, event_type, payload, retry_count
FROM outbox_events
WHERE processed_at IS NULL
ORDER BY id ASC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type ListPendingOutboxEventsRow struct {
	ID         uint64
	EventType  string
	Payload    json.RawMessage
	RetryCount uint32
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]ListPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEventsRow
	for rows.Next() {
		var i ListPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET processed_at = NOW(6)
WHERE id = ?
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventProcessed, id)
	return err
}
