// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const claimPendingOutboxEventByID = `-- name: ClaimPendingOutboxEventByID :one
SELECT id, event_type, payload, retry_count
FROM outbox_events
WHERE id = ?
  AND processed_at IS NULL
  AND retry_count < ?
FOR UPDATE SKIP LOCKED
`

type ClaimPendingOutboxEventByIDParams struct {
	ID       uint64
	MaxRetry uint32
}

type ClaimPendingOutboxEventByIDRow struct {
	ID         uint64
	EventType  string
	Payload    json.RawMessage
	RetryCount uint32
}

// 指定 ID の未処理イベントを FOR UPDATE SKIP LOCKED で確保（claim）する。
// worker は ListPending で得た候補を1件ずつ本クエリで claim し、handleEvent（MySQL 副作用）と
// MarkProcessed を同一 tx でコミットして exactly-once を担保する。
// ID 指定にすることで、先頭イベントが恒久失敗しても後続を処理でき（head-of-line blocking 回避）、
// SKIP LOCKED と processed_at IS NULL 条件により複数 worker が同一イベントを二重処理しない。
// 既に処理済み or 他 worker がロック中 or retry 上限到達は sql.ErrNoRows（該当なし）。
//
// retry_count の条件を ListPending と揃えるのは、候補取得と claim のあいだに別 worker が
// 上限へ到達させた場合に打ち切り済みイベントを掴まないようにするため。
func (q *Queries) ClaimPendingOutboxEventByID(ctx context.Context, arg ClaimPendingOutboxEventByIDParams) (ClaimPendingOutboxEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, claimPendingOutboxEventByID, arg.ID, arg.MaxRetry)
	var i ClaimPendingOutboxEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.RetryCount,
	)
	return i, err
}

const deleteProcessedOutboxEventsBefore = `-- name: DeleteProcessedOutboxEventsBefore :execrows
DELETE FROM outbox_events
WHERE processed_at IS NOT NULL
  AND processed_at < NOW(6) - INTERVAL ? SECOND
ORDER BY processed_at
LIMIT ?
`

type DeleteProcessedOutboxEventsBeforeParams struct {
	RetentionSeconds interface{}
	Limit            int32
}

// 処理済みイベントのうち、保持期間（秒）より古いものを最大 LIMIT 件削除する。
//
// 基準時刻は Go 側から渡さず SQL 側の NOW(6) で取る。アプリ側で現在時刻を取得すると
// AGENTS.md §2 の Clock DI 規約に抵触し、時刻依存でテストが不安定になるため。
//
// LIMIT で分割するのは、1文で全削除すると undo ログとロック保持が肥大して
// 同じテーブルへの INSERT（リクエスト経路の outbox 記録）を阻害するため。
// ORDER BY を idx_outbox_events_pending の先頭列に合わせ、古い順に消していく。
//
// processed_at IS NULL（未処理）は対象外。恒久失敗イベントの始末は
// max retry / DLQ の責務であり、GC が消すとイベントが黙って失われる。
func (q *Queries) DeleteProcessedOutboxEventsBefore(ctx context.Context, arg DeleteProcessedOutboxEventsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProcessedOutboxEventsBefore, arg.RetentionSeconds, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOutboxEventRetryCount = `-- name: GetOutboxEventRetryCount :one
SELECT retry_count
FROM outbox_events
WHERE id = ?
`

// 加算後の retry_count を読み直すためのクエリ。IncrementOutboxEventRetry と同一
// トランザクションで呼ぶ前提で、UPDATE が取った排他ロックの下で自分の更新結果を読む。
//
// MySQL には UPDATE ... RETURNING が無いため2文に分ける。呼び出し側が claim 時点の
// スナップショット値に +1 して代用すると、複数 worker が同じイベントを再 claim した際に
// 実際の値とずれる（打ち切り遷移の検知が二重に出る / 一度も出ない）。
func (q *Queries) GetOutboxEventRetryCount(ctx context.Context, id uint64) (uint32, error) {
	row := q.db.QueryRowContext(ctx, getOutboxEventRetryCount, id)
	var retry_count uint32
	err := row.Scan(&retry_count)
	return retry_count, err
}

const incrementOutboxEventRetry = `-- name: IncrementOutboxEventRetry :exec
UPDATE outbox_events
SET retry_count = retry_count + 1,
    last_error  = ?
WHERE id = ?
`

type IncrementOutboxEventRetryParams struct {
	LastError sql.NullString
	ID        uint64
}

func (q *Queries) IncrementOutboxEventRetry(ctx context.Context, arg IncrementOutboxEventRetryParams) error {
	_, err := q.db.ExecContext(ctx, incrementOutboxEventRetry, arg.LastError, arg.ID)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :execlastid
INSERT INTO outbox_events (event_type, payload)
VALUES (?, ?)
`

type InsertOutboxEventParams struct {
	EventType string
	Payload   json.RawMessage
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOutboxEvent, arg.EventType, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, event_type, payload, retry_count
FROM outbox_events
WHERE processed_at IS NULL
  AND retry_count < ?
ORDER BY id ASC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type ListPendingOutboxEventsParams struct {
	MaxRetry uint32
	Limit    int32
}

type ListPendingOutboxEventsRow struct {
	ID         uint64
	EventType  string
	Payload    json.RawMessage
	RetryCount uint32
}

// 複数 worker をスケールアウトしたときの競合回避で skip locked を付与する。
//
// retry_count が上限に達したイベント（poison）は候補から外す。除外しないと、
// 決して成功しないイベントが窓の先頭を占め続けて後続が永久に処理されない
// （head-of-line blocking）。詳細は docs/testing/outbox-worker.md §0-4。
//
// インデックスは idx_outbox_events_pending (processed_at, id) のまま使い、
// retry_count は index に足さない。足すと ORDER BY id の順序走査が崩れ、
// 「古い順に処理する」ために別途ソートが必要になる。除外対象は例外的に少ない前提で、
// index で絞った行に対する後段フィルタとして評価させる。
func (q *Queries) ListPendingOutboxEvents(ctx context.Context, arg ListPendingOutboxEventsParams) ([]ListPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxEvents, arg.MaxRetry, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEventsRow
	for rows.Next() {
		var i ListPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET processed_at = NOW(6)
WHERE id = ?
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventProcessed, id)
	return err
}

const markOutboxEventsProcessedByIDs = `-- name: MarkOutboxEventsProcessedByIDs :exec
UPDATE outbox_events
SET processed_at = NOW(6)
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) MarkOutboxEventsProcessedByIDs(ctx context.Context, ids []uint64) error {
	query := markOutboxEventsProcessedByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
