// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetGuild(ctx context.Context, id int64) (Guild, error)
	GetGuildScore(ctx context.Context, guildID int64) (GuildScore, error)
	GetGuildScoreForUpdate(ctx context.Context, guildID int64) (GuildScore, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// ユーザー行を排他ロックで取得する。10連ガチャの整合性確保用。
	// 必ずトランザクション内から呼び出すこと。デッドロック誘発検証のため意図的に FOR UPDATE。
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
	GetUserPoints(ctx context.Context, userID int64) (UserPoint, error)
	GetUserPointsForUpdate(ctx context.Context, userID int64) (UserPoint, error)
	IncrementGuildScore(ctx context.Context, arg IncrementGuildScoreParams) error
	IncrementUserPoints(ctx context.Context, arg IncrementUserPointsParams) error
	// ガチャ履歴を1件追加する。
	InsertGachaHistory(ctx context.Context, arg InsertGachaHistoryParams) error
	InsertGuildScoreHistory(ctx context.Context, arg InsertGuildScoreHistoryParams) error
	InsertUserPointHistory(ctx context.Context, arg InsertUserPointHistoryParams) error
	IsUserInGuild(ctx context.Context, arg IsUserInGuildParams) (bool, error)
	ListAllGuildScores(ctx context.Context) ([]GuildScore, error)
	ListAllUserPoints(ctx context.Context) ([]UserPoint, error)
	ListGuildsByIDs(ctx context.Context, ids []int64) ([]Guild, error)
	// アイテムマスタ全件を取得する（排出抽選用）。
	ListItems(ctx context.Context) ([]Item, error)
	ListUsersByIDs(ctx context.Context, ids []int64) ([]User, error)
	// 指定ユーザーの石残高を更新する。トランザクション内から呼び出す前提。
	UpdateUserGems(ctx context.Context, arg UpdateUserGemsParams) error
	UpsertGuildScore(ctx context.Context, arg UpsertGuildScoreParams) error
	// ユーザー所持アイテムを追加。既に存在する場合は所持数を加算する。
	UpsertUserItem(ctx context.Context, arg UpsertUserItemParams) error
	UpsertUserPoints(ctx context.Context, arg UpsertUserPointsParams) error
}

var _ Querier = (*Queries)(nil)
