// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ranking.sql

package sqlc

import (
	"context"
	"strings"
)

const getGuild = `-- name: GetGuild :one
SELECT id, name, created_at, updated_at
FROM guilds
WHERE id = ?
`

func (q *Queries) GetGuild(ctx context.Context, id int64) (Guild, error) {
	row := q.db.QueryRowContext(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuildScore = `-- name: GetGuildScore :one
SELECT guild_id, score, updated_at
FROM guild_scores
WHERE guild_id = ?
`

func (q *Queries) GetGuildScore(ctx context.Context, guildID int64) (GuildScore, error) {
	row := q.db.QueryRowContext(ctx, getGuildScore, guildID)
	var i GuildScore
	err := row.Scan(&i.GuildID, &i.Score, &i.UpdatedAt)
	return i, err
}

const getGuildScoreForUpdate = `-- name: GetGuildScoreForUpdate :one
SELECT guild_id, score, updated_at
FROM guild_scores
WHERE guild_id = ?
FOR UPDATE
`

func (q *Queries) GetGuildScoreForUpdate(ctx context.Context, guildID int64) (GuildScore, error) {
	row := q.db.QueryRowContext(ctx, getGuildScoreForUpdate, guildID)
	var i GuildScore
	err := row.Scan(&i.GuildID, &i.Score, &i.UpdatedAt)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, gem_num, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GemNum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGuildID = `-- name: GetUserGuildID :one
SELECT guild_id
FROM guild_members
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetUserGuildID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserGuildID, userID)
	var guild_id int64
	err := row.Scan(&guild_id)
	return guild_id, err
}

const getUserPoints = `-- name: GetUserPoints :one
SELECT user_id, points, updated_at
FROM user_points
WHERE user_id = ?
`

func (q *Queries) GetUserPoints(ctx context.Context, userID int64) (UserPoint, error) {
	row := q.db.QueryRowContext(ctx, getUserPoints, userID)
	var i UserPoint
	err := row.Scan(&i.UserID, &i.Points, &i.UpdatedAt)
	return i, err
}

const getUserPointsForUpdate = `-- name: GetUserPointsForUpdate :one
SELECT user_id, points, updated_at
FROM user_points
WHERE user_id = ?
FOR UPDATE
`

func (q *Queries) GetUserPointsForUpdate(ctx context.Context, userID int64) (UserPoint, error) {
	row := q.db.QueryRowContext(ctx, getUserPointsForUpdate, userID)
	var i UserPoint
	err := row.Scan(&i.UserID, &i.Points, &i.UpdatedAt)
	return i, err
}

const incrementGuildScore = `-- name: IncrementGuildScore :exec
INSERT INTO guild_scores (guild_id, score)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE score = score + VALUES(score)
`

type IncrementGuildScoreParams struct {
	GuildID int64
	Score   int64
}

func (q *Queries) IncrementGuildScore(ctx context.Context, arg IncrementGuildScoreParams) error {
	_, err := q.db.ExecContext(ctx, incrementGuildScore, arg.GuildID, arg.Score)
	return err
}

const incrementUserPoints = `-- name: IncrementUserPoints :exec
INSERT INTO user_points (user_id, points)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE points = points + VALUES(points)
`

type IncrementUserPointsParams struct {
	UserID int64
	Points int64
}

func (q *Queries) IncrementUserPoints(ctx context.Context, arg IncrementUserPointsParams) error {
	_, err := q.db.ExecContext(ctx, incrementUserPoints, arg.UserID, arg.Points)
	return err
}

const insertGuildScoreHistory = `-- name: InsertGuildScoreHistory :exec
INSERT INTO guild_score_histories (guild_id, user_id, score)
VALUES (?, ?, ?)
`

type InsertGuildScoreHistoryParams struct {
	GuildID int64
	UserID  int64
	Score   int64
}

func (q *Queries) InsertGuildScoreHistory(ctx context.Context, arg InsertGuildScoreHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertGuildScoreHistory, arg.GuildID, arg.UserID, arg.Score)
	return err
}

const insertUserPointHistory = `-- name: InsertUserPointHistory :exec
INSERT INTO user_point_histories (user_id, points, reason)
VALUES (?, ?, ?)
`

type InsertUserPointHistoryParams struct {
	UserID int64
	Points int64
	Reason string
}

func (q *Queries) InsertUserPointHistory(ctx context.Context, arg InsertUserPointHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertUserPointHistory, arg.UserID, arg.Points, arg.Reason)
	return err
}

const isUserInGuild = `-- name: IsUserInGuild :one
SELECT COUNT(*) > 0 AS is_member
FROM guild_members
WHERE guild_id = ? AND user_id = ?
`

type IsUserInGuildParams struct {
	GuildID int64
	UserID  int64
}

func (q *Queries) IsUserInGuild(ctx context.Context, arg IsUserInGuildParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserInGuild, arg.GuildID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listAllGuildScores = `-- name: ListAllGuildScores :many
SELECT guild_id, score, updated_at
FROM guild_scores
ORDER BY score DESC
`

func (q *Queries) ListAllGuildScores(ctx context.Context) ([]GuildScore, error) {
	rows, err := q.db.QueryContext(ctx, listAllGuildScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildScore
	for rows.Next() {
		var i GuildScore
		if err := rows.Scan(&i.GuildID, &i.Score, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUserPoints = `-- name: ListAllUserPoints :many
SELECT user_id, points, updated_at
FROM user_points
ORDER BY points DESC
`

func (q *Queries) ListAllUserPoints(ctx context.Context) ([]UserPoint, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPoint
	for rows.Next() {
		var i UserPoint
		if err := rows.Scan(&i.UserID, &i.Points, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildsByIDs = `-- name: ListGuildsByIDs :many
SELECT id, name, created_at, updated_at
FROM guilds
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListGuildsByIDs(ctx context.Context, ids []int64) ([]Guild, error) {
	query := listGuildsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guild
	for rows.Next() {
		var i Guild
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, name, gem_num, created_at, updated_at
FROM users
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	query := listUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GemNum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuildScore = `-- name: UpsertGuildScore :exec
INSERT INTO guild_scores (guild_id, score)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE score = VALUES(score)
`

type UpsertGuildScoreParams struct {
	GuildID int64
	Score   int64
}

func (q *Queries) UpsertGuildScore(ctx context.Context, arg UpsertGuildScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuildScore, arg.GuildID, arg.Score)
	return err
}

const upsertUserPoints = `-- name: UpsertUserPoints :exec
INSERT INTO user_points (user_id, points)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE points = VALUES(points)
`

type UpsertUserPointsParams struct {
	UserID int64
	Points int64
}

func (q *Queries) UpsertUserPoints(ctx context.Context, arg UpsertUserPointsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPoints, arg.UserID, arg.Points)
	return err
}
