// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mock/mock_querier.go -package=mock_sqlc
//

// Package mock_sqlc is a generated GoMock package.
package mock_sqlc

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/uchidas-rogue/game-api-sample/internal/infrastructure/mysql/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetUserForUpdate mocks base method.
func (m *MockQuerier) GetUserForUpdate(ctx context.Context, id int64) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdate", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdate indicates an expected call of GetUserForUpdate.
func (mr *MockQuerierMockRecorder) GetUserForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetUserForUpdate), ctx, id)
}

// InsertGachaHistory mocks base method.
func (m *MockQuerier) InsertGachaHistory(ctx context.Context, arg sqlc.InsertGachaHistoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGachaHistory", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGachaHistory indicates an expected call of InsertGachaHistory.
func (mr *MockQuerierMockRecorder) InsertGachaHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGachaHistory", reflect.TypeOf((*MockQuerier)(nil).InsertGachaHistory), ctx, arg)
}

// ListItems mocks base method.
func (m *MockQuerier) ListItems(ctx context.Context) ([]sqlc.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx)
	ret0, _ := ret[0].([]sqlc.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockQuerierMockRecorder) ListItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockQuerier)(nil).ListItems), ctx)
}

// UpdateUserGems mocks base method.
func (m *MockQuerier) UpdateUserGems(ctx context.Context, arg sqlc.UpdateUserGemsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGems", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGems indicates an expected call of UpdateUserGems.
func (mr *MockQuerierMockRecorder) UpdateUserGems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGems", reflect.TypeOf((*MockQuerier)(nil).UpdateUserGems), ctx, arg)
}

// UpsertUserItem mocks base method.
func (m *MockQuerier) UpsertUserItem(ctx context.Context, arg sqlc.UpsertUserItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserItem indicates an expected call of UpsertUserItem.
func (mr *MockQuerierMockRecorder) UpsertUserItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserItem", reflect.TypeOf((*MockQuerier)(nil).UpsertUserItem), ctx, arg)
}
