// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	reflect "reflect"
	time "time"

	outbox "github.com/uchidas-rogue/game-api-sample/internal/domain/outbox"
	shared "github.com/uchidas-rogue/game-api-sample/internal/usecase/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ClaimByID mocks base method.
func (m *MockRepository) ClaimByID(ctx context.Context, tx shared.Tx, id uint64) (outbox.Event, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimByID", ctx, tx, id)
	ret0, _ := ret[0].(outbox.Event)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimByID indicates an expected call of ClaimByID.
func (mr *MockRepositoryMockRecorder) ClaimByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimByID", reflect.TypeOf((*MockRepository)(nil).ClaimByID), ctx, tx, id)
}

// DeleteProcessedBefore mocks base method.
func (m *MockRepository) DeleteProcessedBefore(ctx context.Context, tx shared.Tx, retention time.Duration, limit int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessedBefore", ctx, tx, retention, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProcessedBefore indicates an expected call of DeleteProcessedBefore.
func (mr *MockRepositoryMockRecorder) DeleteProcessedBefore(ctx, tx, retention, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessedBefore", reflect.TypeOf((*MockRepository)(nil).DeleteProcessedBefore), ctx, tx, retention, limit)
}

// IncrementRetry mocks base method.
func (m *MockRepository) IncrementRetry(ctx context.Context, tx shared.Tx, id uint64, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetry", ctx, tx, id, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetry indicates an expected call of IncrementRetry.
func (mr *MockRepositoryMockRecorder) IncrementRetry(ctx, tx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetry", reflect.TypeOf((*MockRepository)(nil).IncrementRetry), ctx, tx, id, lastError)
}

// InsertEvent mocks base method.
func (m *MockRepository) InsertEvent(ctx context.Context, tx shared.Tx, eventType outbox.EventType, payload []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, tx, eventType, payload)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockRepositoryMockRecorder) InsertEvent(ctx, tx, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockRepository)(nil).InsertEvent), ctx, tx, eventType, payload)
}

// ListPending mocks base method.
func (m *MockRepository) ListPending(ctx context.Context, tx shared.Tx, limit int32) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, tx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockRepositoryMockRecorder) ListPending(ctx, tx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockRepository)(nil).ListPending), ctx, tx, limit)
}

// MarkProcessed mocks base method.
func (m *MockRepository) MarkProcessed(ctx context.Context, tx shared.Tx, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockRepositoryMockRecorder) MarkProcessed(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockRepository)(nil).MarkProcessed), ctx, tx, id)
}

// MarkProcessedByIDs mocks base method.
func (m *MockRepository) MarkProcessedByIDs(ctx context.Context, tx shared.Tx, ids []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessedByIDs", ctx, tx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessedByIDs indicates an expected call of MarkProcessedByIDs.
func (mr *MockRepositoryMockRecorder) MarkProcessedByIDs(ctx, tx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessedByIDs", reflect.TypeOf((*MockRepository)(nil).MarkProcessedByIDs), ctx, tx, ids)
}
