// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	reflect "reflect"

	outbox "github.com/uchidas-rogue/game-api-sample/internal/domain/outbox"
	shared "github.com/uchidas-rogue/game-api-sample/internal/usecase/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetMaxID mocks base method.
func (m *MockRepository) GetMaxID(ctx context.Context, tx shared.Tx) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxID", ctx, tx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxID indicates an expected call of GetMaxID.
func (mr *MockRepositoryMockRecorder) GetMaxID(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxID", reflect.TypeOf((*MockRepository)(nil).GetMaxID), ctx, tx)
}

// IncrementRetry mocks base method.
func (m *MockRepository) IncrementRetry(ctx context.Context, tx shared.Tx, id uint64, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetry", ctx, tx, id, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetry indicates an expected call of IncrementRetry.
func (mr *MockRepositoryMockRecorder) IncrementRetry(ctx, tx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetry", reflect.TypeOf((*MockRepository)(nil).IncrementRetry), ctx, tx, id, lastError)
}

// InsertEvent mocks base method.
func (m *MockRepository) InsertEvent(ctx context.Context, tx shared.Tx, eventType outbox.EventType, payload []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, tx, eventType, payload)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockRepositoryMockRecorder) InsertEvent(ctx, tx, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockRepository)(nil).InsertEvent), ctx, tx, eventType, payload)
}

// ListPending mocks base method.
func (m *MockRepository) ListPending(ctx context.Context, tx shared.Tx, limit int32) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, tx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockRepositoryMockRecorder) ListPending(ctx, tx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockRepository)(nil).ListPending), ctx, tx, limit)
}

// MarkProcessed mocks base method.
func (m *MockRepository) MarkProcessed(ctx context.Context, tx shared.Tx, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockRepositoryMockRecorder) MarkProcessed(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockRepository)(nil).MarkProcessed), ctx, tx, id)
}

// MarkProcessedUpTo mocks base method.
func (m *MockRepository) MarkProcessedUpTo(ctx context.Context, tx shared.Tx, maxID uint64, eventType outbox.EventType) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessedUpTo", ctx, tx, maxID, eventType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkProcessedUpTo indicates an expected call of MarkProcessedUpTo.
func (mr *MockRepositoryMockRecorder) MarkProcessedUpTo(ctx, tx, maxID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessedUpTo", reflect.TypeOf((*MockRepository)(nil).MarkProcessedUpTo), ctx, tx, maxID, eventType)
}
