// Code generated by fixture. DO NOT EDIT.

// 生成マーカーがあるので検査対象外。マーカーが無ければ ng_separated.go と同じ違反になる。
package fixture

type ifaceI interface{ DoI() }

var _ ifaceI = (*implI)(nil)

func helperI() {}

type implI struct{}
