// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -source=transaction.go -destination=mock/mock_transaction.go -package=mock_shared
//

// Package mock_shared is a generated GoMock package.
package mock_shared

import (
	context "context"
	reflect "reflect"

	shared "github.com/uchidas-rogue/game-api-sample/internal/usecase/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
	isgomock struct{}
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// IsTx mocks base method.
func (m *MockTx) IsTx() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsTx")
}

// IsTx indicates an expected call of IsTx.
func (mr *MockTxMockRecorder) IsTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTx", reflect.TypeOf((*MockTx)(nil).IsTx))
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// DoInTx mocks base method.
func (m *MockTransactor) DoInTx(ctx context.Context, fn func(shared.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoInTx indicates an expected call of DoInTx.
func (mr *MockTransactorMockRecorder) DoInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTx", reflect.TypeOf((*MockTransactor)(nil).DoInTx), ctx, fn)
}
