// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mock/mock_usecase.go -package=mock_gacha
//

// Package mock_gacha is a generated GoMock package.
package mock_gacha

import (
	context "context"
	reflect "reflect"

	gacha "github.com/uchidas-rogue/game-api-sample/internal/usecase/gacha"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// DoInTx mocks base method.
func (m *MockTransactor) DoInTx(ctx context.Context, fn func(gacha.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoInTx indicates an expected call of DoInTx.
func (mr *MockTransactorMockRecorder) DoInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTx", reflect.TypeOf((*MockTransactor)(nil).DoInTx), ctx, fn)
}

// MockRandomizer is a mock of Randomizer interface.
type MockRandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockRandomizerMockRecorder
	isgomock struct{}
}

// MockRandomizerMockRecorder is the mock recorder for MockRandomizer.
type MockRandomizerMockRecorder struct {
	mock *MockRandomizer
}

// NewMockRandomizer creates a new mock instance.
func NewMockRandomizer(ctrl *gomock.Controller) *MockRandomizer {
	mock := &MockRandomizer{ctrl: ctrl}
	mock.recorder = &MockRandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandomizer) EXPECT() *MockRandomizerMockRecorder {
	return m.recorder
}

// IntN mocks base method.
func (m *MockRandomizer) IntN(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntN", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntN indicates an expected call of IntN.
func (mr *MockRandomizerMockRecorder) IntN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntN", reflect.TypeOf((*MockRandomizer)(nil).IntN), n)
}

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Multi mocks base method.
func (m *MockUsecase) Multi(ctx context.Context, userID int64, pullCount int) (gacha.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Multi", ctx, userID, pullCount)
	ret0, _ := ret[0].(gacha.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Multi indicates an expected call of Multi.
func (mr *MockUsecaseMockRecorder) Multi(ctx, userID, pullCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Multi", reflect.TypeOf((*MockUsecase)(nil).Multi), ctx, userID, pullCount)
}
