// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock_gacha
//

// Package mock_gacha is a generated GoMock package.
package mock_gacha

import (
	context "context"
	reflect "reflect"

	gacha "github.com/uchidas-rogue/game-api-sample/internal/domain/gacha"
	gacha0 "github.com/uchidas-rogue/game-api-sample/internal/usecase/gacha"
	shared "github.com/uchidas-rogue/game-api-sample/internal/usecase/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserForUpdate mocks base method.
func (m *MockRepository) GetUserForUpdate(ctx context.Context, tx shared.Tx, userID int64) (gacha.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdate", ctx, tx, userID)
	ret0, _ := ret[0].(gacha.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdate indicates an expected call of GetUserForUpdate.
func (mr *MockRepositoryMockRecorder) GetUserForUpdate(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdate", reflect.TypeOf((*MockRepository)(nil).GetUserForUpdate), ctx, tx, userID)
}

// InsertGachaHistories mocks base method.
func (m *MockRepository) InsertGachaHistories(ctx context.Context, tx shared.Tx, userID int64, itemIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGachaHistories", ctx, tx, userID, itemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGachaHistories indicates an expected call of InsertGachaHistories.
func (mr *MockRepositoryMockRecorder) InsertGachaHistories(ctx, tx, userID, itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGachaHistories", reflect.TypeOf((*MockRepository)(nil).InsertGachaHistories), ctx, tx, userID, itemIDs)
}

// ListItems mocks base method.
func (m *MockRepository) ListItems(ctx context.Context, tx shared.Tx) ([]gacha.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, tx)
	ret0, _ := ret[0].([]gacha.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockRepositoryMockRecorder) ListItems(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockRepository)(nil).ListItems), ctx, tx)
}

// UpdateUserGems mocks base method.
func (m *MockRepository) UpdateUserGems(ctx context.Context, tx shared.Tx, userID int64, newGems int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGems", ctx, tx, userID, newGems)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGems indicates an expected call of UpdateUserGems.
func (mr *MockRepositoryMockRecorder) UpdateUserGems(ctx, tx, userID, newGems any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGems", reflect.TypeOf((*MockRepository)(nil).UpdateUserGems), ctx, tx, userID, newGems)
}

// UpsertUserItems mocks base method.
func (m *MockRepository) UpsertUserItems(ctx context.Context, tx shared.Tx, userID int64, items []gacha0.UserItemCount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserItems", ctx, tx, userID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserItems indicates an expected call of UpsertUserItems.
func (mr *MockRepositoryMockRecorder) UpsertUserItems(ctx, tx, userID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserItems", reflect.TypeOf((*MockRepository)(nil).UpsertUserItems), ctx, tx, userID, items)
}
