// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock_gacha
//

// Package mock_gacha is a generated GoMock package.
package mock_gacha

import (
	context "context"
	reflect "reflect"

	gacha "github.com/uchidas-rogue/game-api-sample/internal/domain/gacha"
	gacha0 "github.com/uchidas-rogue/game-api-sample/internal/usecase/gacha"
	gomock "go.uber.org/mock/gomock"
)

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
	isgomock struct{}
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// IsTx mocks base method.
func (m *MockTx) IsTx() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsTx")
}

// IsTx indicates an expected call of IsTx.
func (mr *MockTxMockRecorder) IsTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTx", reflect.TypeOf((*MockTx)(nil).IsTx))
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserForUpdate mocks base method.
func (m *MockRepository) GetUserForUpdate(ctx context.Context, tx gacha0.Tx, userID int64) (gacha.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdate", ctx, tx, userID)
	ret0, _ := ret[0].(gacha.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdate indicates an expected call of GetUserForUpdate.
func (mr *MockRepositoryMockRecorder) GetUserForUpdate(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdate", reflect.TypeOf((*MockRepository)(nil).GetUserForUpdate), ctx, tx, userID)
}

// InsertGachaHistory mocks base method.
func (m *MockRepository) InsertGachaHistory(ctx context.Context, tx gacha0.Tx, userID, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGachaHistory", ctx, tx, userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGachaHistory indicates an expected call of InsertGachaHistory.
func (mr *MockRepositoryMockRecorder) InsertGachaHistory(ctx, tx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGachaHistory", reflect.TypeOf((*MockRepository)(nil).InsertGachaHistory), ctx, tx, userID, itemID)
}

// ListItems mocks base method.
func (m *MockRepository) ListItems(ctx context.Context, tx gacha0.Tx) ([]gacha.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, tx)
	ret0, _ := ret[0].([]gacha.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockRepositoryMockRecorder) ListItems(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockRepository)(nil).ListItems), ctx, tx)
}

// UpdateUserGems mocks base method.
func (m *MockRepository) UpdateUserGems(ctx context.Context, tx gacha0.Tx, userID int64, newGems int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGems", ctx, tx, userID, newGems)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGems indicates an expected call of UpdateUserGems.
func (mr *MockRepositoryMockRecorder) UpdateUserGems(ctx, tx, userID, newGems any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGems", reflect.TypeOf((*MockRepository)(nil).UpdateUserGems), ctx, tx, userID, newGems)
}

// UpsertUserItem mocks base method.
func (m *MockRepository) UpsertUserItem(ctx context.Context, tx gacha0.Tx, userID, itemID int64, num int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserItem", ctx, tx, userID, itemID, num)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserItem indicates an expected call of UpsertUserItem.
func (mr *MockRepositoryMockRecorder) UpsertUserItem(ctx, tx, userID, itemID, num any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserItem", reflect.TypeOf((*MockRepository)(nil).UpsertUserItem), ctx, tx, userID, itemID, num)
}
